spring:
  application:
    name: PizzarIO
  config:
    import:
      - optional:classpath:env.properties
      - optional:file:./config/manager-settings.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    defer-datasource-initialization: true
  devtools:
    add-properties: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      mode: always
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  profiles:
    active: prod

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
    session:
      cookie:
        http-only: true #cookie k thể truy cập từ Javascript (chống XSS)
        secure: false
        same-site: lax #Chống CSRF
      timeout: 30m

logging:
  level:
    com.group1.swp.pizzario_swp391.service.StaffScheduleService: DEBUG
    com.group1.swp.pizzario_swp391.service.StaffShiftManagementService: DEBUG
    org.springframework.context.event: DEBUG

gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: ${GEMINI_MODEL}

pizzario:
  settings-file-path: ./config/manager-settings.yaml
